CREATE TABLE `comanda`.`usuarios` ( `id` INT NOT NULL AUTO_INCREMENT , `username` VARCHAR(100) NOT NULL , `user_password` VARCHAR(500) NOT NULL , `rol` VARCHAR(100) NOT NULL , `area` VARCHAR(100) NOT NULL , `user_status` VARCHAR(70) NOT NULL , `createdAt` VARCHAR(100) NOT NULL , `deletedAt` VARCHAR(100) NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `comanda`.`tables` ( `id` INT NOT NULL AUTO_INCREMENT , `table_number` INT(10) NOT NULL , `table_status` VARCHAR(70) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `comanda`.`products` ( `id` INT NOT NULL AUTO_INCREMENT , `productName` VARCHAR(70) NOT NULL , `product_type` VARCHAR(70) NOT NULL , `price` INT(30) NOT NULL , `description` VARCHAR(150) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `comanda`.`orders` ( `id` INT NOT NULL AUTO_INCREMENT , `table_id` INT(20) NOT NULL , `user_id` INT(20) NOT NULL , `product_id` INT(20) NOT NULL , `status` VARCHAR(70) NOT NULL , `createdAt` VARCHAR(70) NOT NULL , `estimatedTime` VARCHAR(70) NULL , `finalPrice` INT(50) NOT NULL , `orderNumber` INT(30) NOT NULL , `picture` VARCHAR(200) NOT NULL , `finishAt` VARCHAR(100) NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `comanda`.`historic_accions` ( `id` INT NOT NULL AUTO_INCREMENT , `user_id` INT(50) NOT NULL , `accion` VARCHAR(100) NOT NULL , `createdAt` VARCHAR(100) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `comanda`.`surveys` ( `id` INT(20) NOT NULL AUTO_INCREMENT , `id_table` INT(50) NOT NULL , `score_table` INT(50) NOT NULL , `score_restarnt` INT(50) NOT NULL , `score_waiter` INT(50) NOT NULL , `score_chef` INT(50) NOT NULL , `comments` VARCHAR(500) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

INSERT INTO `tables` (`id`, `table_number`, `table_status`) VALUES ('1', '00001', 'vacia'), ('2', '00002', 'vacia'), ('3', '00003', 'con cliente esperando pedido'), ('4', '00004', 'con cliente esperando pedido'), ('5', '00005', 'con cliente comiendo'), ('6', '00006', 'con cliente comiendo'), ('7', '00007', 'con cliente pagando'), ('8', '00008', 'con cliente pagando'), ('9', '00009', 'vacia'), ('10', '00010', 'vacia');

INSERT INTO `products` (`id`, `productName`, `product_type`, `price`, `description`) VALUES ('1', 'Milanesa con Fritas', 'Plato Principal', '1500', 'Milanesa de ternera con fritas a la provenzal'), ('2', 'Fideos con Salsa a eleccion', 'Plato Principal', '800', 'Fideos con Salsa (roja, blanca, pesto o cualquiera de las 3)'), ('3', 'Asado para 4', 'Plato Principal', '5000', 'Asado completo para 4 personas'), ('4', 'Hamburguesa con Cheddar y Bacon', 'Plato Principal', '1250', 'Doble hamburguesa con cheddar y bacon y condimentos a eleccion'), ('5', 'Pizza de Muzzarella', 'Plato Principal', '1300', 'Pizza a la piedra de muzza'), ('6', 'Cerveza Corona', 'Bebida', '500', 'Cerveza Corona de 1L'), ('7', 'Coca Cola de 2.5L', 'Bebida', '600', 'Coca Cola de 2.5L'), ('8', 'Agua sin gas', 'Bebida', '230', 'Agua sin gas de 1L'), ('9', 'Flan con DDL', 'Postre', '230', 'Flan con DDL'), ('10', 'Frutillas con Crema', 'Postre', '300', 'Frutillas con Crema'), ('11', 'Agua saborizada', 'Bebida', '250', 'Agua saborizada'), ('12', 'Cafe expresso', 'Cafeteria', '130', 'Cafe expresso'), ('13', 'Tecito', 'Cafeteria', '70', 'Tecito'), ('14', 'Medialunas', 'Cafeteria', '50', 'Medialunas de manteca o grasa'), ('15', 'Tostados de JYQ', 'Cafeteria', '180', 'Tostados de JYQ');